version: '3.1'

services:
  app:
    build: .
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/First_Book_Store
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=

  db:
    image: 'mysql:latest'
    container_name: db
    environment:
      MYSQL_DATABASE: First_Book_Store
      MYSQL_USER:
      MYSQL_PASSWORD:
